//register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

//login user
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// get all subcategories
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";
export const GET_SUBCATEGORIES_SUCCESS = "GET_SUBCATEGORIES_SUCCESS";
export const GET_SUBCATEGORIES_FAIL = "GET_SUBCATEGORIES_FAIL";

// get all services
export const GET_SERVICES = "GET_SERVICES";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAIL = "GET_SERVICES_FAIL";

// get service based by subcategories
export const GET_SERVICE_BY_SUBCATEGORY = "GET_SERVICE_BY_SUBCATEGORY";
export const GET_SERVICE_BY_SUBCATEGORY_SUCCESS = "GET_SERVICE_BY_SUBCATEGORY_SUCCESS";
export const GET_SERVICE_BY_SUBCATEGORY_FAIL = "GET_SERVICE_BY_SUBCATEGORY_FAIL";
